class OptionsExceptionBase(Exception):pass

class OptionsExceptionFailedValidation(OptionsExceptionBase):pass

class OptionsExceptionIncompatibleTypes(OptionsExceptionBase):pass

class OptionsExceptionNoAllowed(OptionsExceptionBase):pass

class OptionsExceptionEmptyOptionValues(OptionsExceptionBase):pass

class OptionsExceptionMissingInterfaceMethod(OptionsExceptionBase):pass