class OptionsExceptionBase(Exception):pass

class OptionsExceptionFailedValidation(OptionsExceptionBase):pass

class OptionsExceptionIncompatibleTypes(OptionsExceptionBase):pass

class OptionsExceptionNotAllowed(OptionsExceptionBase):pass

class OptionsExceptionEmptyOptionValues(OptionsExceptionBase):pass

class OptionsExceptionMissingInterfaceMethod(OptionsExceptionBase):pass

class OptionsExceptionReferenceError(OptionsExceptionBase):pass

class OptionsExceptionKeyError(OptionsExceptionBase):pass